TimeScaleDb:
 Host: 172.24.0.2
 Port: 5432
 Login: postgres
 Password: postgres
 DB: postgres 
 ConnMaxLifeTime: 3
 MaxOpenConn: 10
 MaxIdleConn: 10
 SSLMode: disable
Kafka:
 Brokers: ["192.168.1.9:29092"]
 Topic: helll
 Partition: 0
 GroupID: "group-id"
 ReadFrom: another