TimeScaleDb:
 Host: 192.168.1.9
 Port: 5433
 Login: postgres
 Password: postgres
 DB: postgres 
 ConnMaxLifeTime: 3
 MaxOpenConn: 10
 MaxIdleConn: 10
 SSLMode: disable
Kafka:
 Brokers: ["192.168.1.9:29092"]
 Partition: 0
 GroupID: "group-id"
 ReadFrom: another